macro(_bundle_log LEVEL MESSAGE)
  message(${LEVEL} "[bundle] ${MESSAGE}")
endmacro()

function(_bundle_valid_identifier NAME RESULT_VAR)
  if(NAME MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    set(${RESULT_VAR} TRUE PARENT_SCOPE)
  else()
    set(${RESULT_VAR} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(_bundle_detect_os RESULT_VAR)
  if(EMSCRIPTEN)
    set(${RESULT_VAR} "wasm" PARENT_SCOPE)
  elseif(APPLE)
    set(${RESULT_VAR} "macos" PARENT_SCOPE)
  elseif(WIN32)
    set(${RESULT_VAR} "windows" PARENT_SCOPE)
  else()
    set(${RESULT_VAR} "unix" PARENT_SCOPE)
  endif()
endfunction()
